name: Format fastapi source code
on:
  push:
    branches:
      - authen-api

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Format source code
        run: |
          black ./api
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          remote_repo="https://${{ GITHUB_ACTOR }}:${{ GITHUB_TOKEN }}@github.com/${{ GITHUB_REPOSITORY }}.git"
          echo $remote_repo
          git config http.sslVerify false
          git config user.name 'Black Formatter'
          git config --global user.email 'black-formatter@users.noreply.github.com'
          git remote add publisher "${remote_repo}"
          git show-ref
          git branch --verbose
          # git commit -am "Format source code"
          # git push publisher ${{ github.head_ref }}
